//Modal
const OPEN_MODAL = "OPEN_MODAL";
const CLOSE_MODAL = "CLOSE_MODAL";

//Login
const LOGIN_REQUEST = "LOGIN_REQUEST";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAILURE = "LOGIN_FAILURE";

export { OPEN_MODAL, CLOSE_MODAL, LOGIN_REQUEST, LOGIN_SUCCESS, LOGIN_FAILURE };
